### ISSUE TITLE
cd-ing into non-directories

### ISSUE THREAD

**Issue by 1kq2lo40lozpmb63** [KhanAcademyAmateurs/KAnix#2]
Try to `cd` into something that's not a file :o

**Comment by 1kq2lo40lozpmb63** [comment]
Unlike most bugs, I want to fix this ASAP, A.K.A. in v0.1.7 + v0.8c.

**Comment by ghost** [comment]
The problem is in this section of the code:

```
cd: function (a) {
        $.PWD = a[0] ? a[0][0] === "/" ? a[0] : $.PWD + a[0] + "/" : "/";
        return "";
```

We need to check `if (a === directory)` then change the directory.

**Comment by 1kq2lo40lozpmb63** [comment]
Yes, but the check would have to look something like:

```
if (a instanceof Directory) {
    if (writable(a)) {
        change path here
    } else {
        not allowed error here
    }
} else {
    not a directory error here
}
```

**Comment by 1kq2lo40lozpmb63** [comment]
Well, replace `a` with `p` and define `p = getPath(path(a[0]));`

**Comment by 1kq2lo40lozpmb63** [comment]
Till tomorrow.
