### ISSUE TITLE
Copy offline development folder to gh-pages?

### ISSUE THREAD

**Issue by 1kq2lo40lozpmb63** [KhanAcademyAmateurs/KAnix#4]
Could we copy the `offline development` folder to the gh-pages branch? And it's not good practice to put spaces in directory names. Could you rename the directory to `offline-dev`?

I wish I could do this all but I'm on a phone ;(

**Comment by ghost** [comment]
sure, what is the gh-pages branch for?

Should I merge both of the branches?

**Comment by 1kq2lo40lozpmb63** [comment]
The gh-pages branch is the website: https://khanacademyamateurs.github.io/KAnix

**Comment by ghost** [comment]
Do you want me to delete the remaining files and copy all the files from the offline-dev folder to replace the files on the gh-pages branch?

**Comment by 1kq2lo40lozpmb63** [comment]
Yes please.

**Comment by ghost** [comment]
I moved the remaining files to a different folder.

Is that good with you?
